packages:
  - apps/backend
  - apps/frontend/web
  - apps/frontend/mobile
  - packages/*

overrides:
  react: "19.0.0"
  "@types/react": "19.0.10"
  "vite@>=6.0.0 <=6.4.0": ">=6.4.1"
  "vite@>=7.1.0 <=7.1.10": ">=7.1.11"
  "js-yaml@<3.14.2": ">=3.14.2"
  "js-yaml@>=4.0.0 <4.1.1": ">=4.1.1"
  "glob@>=10.2.0 <10.5.0": ">=10.5.0"
  "node-forge@<1.3.2": ">=1.3.2"
  "react-server-dom-webpack@=19.0.0": ">=19.0.1"
  "react-server-dom-webpack@>=19.0.0 <19.0.2": ">=19.0.2"

allowBuilds:
  esbuild: true
  supabase: true
  unrs-resolver: true
