FROM node:20

# Configure PNPM environment
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Enable corepack (makes pnpm available)
RUN corepack enable

# Create app directory
WORKDIR /web

# Copy lockfile and package.json before other files (to cache deps)
COPY pnpm-lock.yaml package.json ./

# Install dependencies
RUN pnpm install

# Copy the rest of the app
COPY . .

# Expose Vite dev server port
EXPOSE 5173

# Start Vite dev server
CMD ["pnpm", "dev"]
