/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutDashboardRouteImport } from './routes/workoutDashboard'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingCompleteRouteImport } from './routes/onboardingComplete'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAppUserRouteImport } from './routes/_auth/app/user'
import { Route as AuthAppSettingsRouteImport } from './routes/_auth/app/settings'
import { Route as AuthAppLibraryRouteImport } from './routes/_auth/app/library'
import { Route as AuthAppHistoryRouteImport } from './routes/_auth/app/history'
import { Route as AuthAppDashboardRouteImport } from './routes/_auth/app/dashboard'

const WorkoutDashboardRoute = WorkoutDashboardRouteImport.update({
  id: '/workoutDashboard',
  path: '/workoutDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboardingComplete',
  path: '/onboardingComplete',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppUserRoute = AuthAppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppSettingsRoute = AuthAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppLibraryRoute = AuthAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppHistoryRoute = AuthAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppDashboardRoute = AuthAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboardingComplete': typeof OnboardingCompleteRoute
  '/signup': typeof SignupRoute
  '/workout': typeof WorkoutRoute
  '/workoutDashboard': typeof WorkoutDashboardRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/app/history': typeof AuthAppHistoryRoute
  '/app/library': typeof AuthAppLibraryRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/app/user': typeof AuthAppUserRoute
  '/app/': typeof AuthAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboardingComplete': typeof OnboardingCompleteRoute
  '/signup': typeof SignupRoute
  '/workout': typeof WorkoutRoute
  '/workoutDashboard': typeof WorkoutDashboardRoute
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/app/history': typeof AuthAppHistoryRoute
  '/app/library': typeof AuthAppLibraryRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/app/user': typeof AuthAppUserRoute
  '/app': typeof AuthAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboardingComplete': typeof OnboardingCompleteRoute
  '/signup': typeof SignupRoute
  '/workout': typeof WorkoutRoute
  '/workoutDashboard': typeof WorkoutDashboardRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/app/dashboard': typeof AuthAppDashboardRoute
  '/_auth/app/history': typeof AuthAppHistoryRoute
  '/_auth/app/library': typeof AuthAppLibraryRoute
  '/_auth/app/settings': typeof AuthAppSettingsRoute
  '/_auth/app/user': typeof AuthAppUserRoute
  '/_auth/app/': typeof AuthAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/onboarding'
    | '/onboardingComplete'
    | '/signup'
    | '/workout'
    | '/workoutDashboard'
    | '/app'
    | '/app/dashboard'
    | '/app/history'
    | '/app/library'
    | '/app/settings'
    | '/app/user'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/onboarding'
    | '/onboardingComplete'
    | '/signup'
    | '/workout'
    | '/workoutDashboard'
    | '/app/dashboard'
    | '/app/history'
    | '/app/library'
    | '/app/settings'
    | '/app/user'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/onboarding'
    | '/onboardingComplete'
    | '/signup'
    | '/workout'
    | '/workoutDashboard'
    | '/_auth/app'
    | '/_auth/app/dashboard'
    | '/_auth/app/history'
    | '/_auth/app/library'
    | '/_auth/app/settings'
    | '/_auth/app/user'
    | '/_auth/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  SignupRoute: typeof SignupRoute
  WorkoutRoute: typeof WorkoutRoute
  WorkoutDashboardRoute: typeof WorkoutDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workoutDashboard': {
      id: '/workoutDashboard'
      path: '/workoutDashboard'
      fullPath: '/workoutDashboard'
      preLoaderRoute: typeof WorkoutDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboardingComplete': {
      id: '/onboardingComplete'
      path: '/onboardingComplete'
      fullPath: '/onboardingComplete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/user': {
      id: '/_auth/app/user'
      path: '/user'
      fullPath: '/app/user'
      preLoaderRoute: typeof AuthAppUserRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/settings': {
      id: '/_auth/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthAppSettingsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/library': {
      id: '/_auth/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AuthAppLibraryRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/history': {
      id: '/_auth/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthAppHistoryRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/dashboard': {
      id: '/_auth/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthAppDashboardRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppDashboardRoute: typeof AuthAppDashboardRoute
  AuthAppHistoryRoute: typeof AuthAppHistoryRoute
  AuthAppLibraryRoute: typeof AuthAppLibraryRoute
  AuthAppSettingsRoute: typeof AuthAppSettingsRoute
  AuthAppUserRoute: typeof AuthAppUserRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppDashboardRoute: AuthAppDashboardRoute,
  AuthAppHistoryRoute: AuthAppHistoryRoute,
  AuthAppLibraryRoute: AuthAppLibraryRoute,
  AuthAppSettingsRoute: AuthAppSettingsRoute,
  AuthAppUserRoute: AuthAppUserRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  SignupRoute: SignupRoute,
  WorkoutRoute: WorkoutRoute,
  WorkoutDashboardRoute: WorkoutDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
