name: Create development builds

jobs:
  android_development_build:
    name: Build Android
    type: build
    workingDirectory: apps/frontend/mobile
    params:
      platform: android
      profile: development
