name: Create development builds

jobs:
  defaults:
    run:
      working_directory: apps/frontend/mobile
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development
