#!/bin/sh

echo "🔒 Scanning backend for secrets..."

cd apps/backend || exit 1
# poetry run detect-secrets-hook --baseline .secrets.baseline
# poetry run detect-secrets scan --all-files app
poetry run detect-secrets scan --baseline ../../.secrets.baseline
status=$?

if [ $status -ne 0 ]; then
  echo "❌ Secrets detected in staged files! Commit blocked."
  exit 1
fi

echo "✅ No secrets detected. Running lint and test..."

cd ../../  # Go back to root
pnpm lint && pnpm test